# Generated by Django 2.2.1 on 2019-05-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right_choise',
            field=models.IntegerField(default=1),
        ),
    ]
