# Generated by Django 2.2.1 on 2019-05-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_question_right_choise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choise_text',
            new_name='choice_text',
        ),
    ]
