# Generated by Django 2.2.1 on 2019-05-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20190529_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='right_choise',
            new_name='right_choice',
        ),
    ]
