# Generated by Django 2.2.1 on 2019-05-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20190529_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bal',
            field=models.IntegerField(default=0),
        ),
    ]
