# Generated by Django 2.2.1 on 2019-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_test_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
